package com.wherefood.web;
import com.wherefood.config.*; import com.wherefood.domain.*; import com.wherefood.repo.Repositories.*; import jakarta.validation.constraints.*; import org.springframework.beans.factory.annotation.*; import org.springframework.http.*; import org.springframework.security.access.prepost.*; import org.springframework.security.core.annotation.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.*; import org.springframework.web.server.ResponseStatusException; import java.io.*; import java.time.*; import java.util.*;

record LoginRequest(@NotBlank String username,@NotBlank String password){} record AuthResponse(String token,String username,String role){}
record CategoryRequest(@NotBlank String name,@NotBlank String slug,@NotBlank String icon,boolean active){} record CategoryDto(Long id,String name,String slug,String icon,boolean active){}
record PlaceRequest(@NotBlank String name,String zone,@NotNull Long categoryId){} record ItemRequest(@NotBlank String name,String comment,@Min(1) @Max(5) short taste,@Min(1) @Max(5) short price,@Min(1) @Max(5) short venue){}
record ItemDto(Long id,String name,String comment,short taste,short price,short venue,String author,String photoUrl,String thumbnailUrl,Instant createdAt){}
record PlaceDto(Long id,String name,String zone,CategoryDto category,String author,double rating,long itemCount,Instant createdAt){} record Slice<T>(List<T> content,Long nextCursor){}

@RestController @RequestMapping("/api") public class Api {
 private final Users users; private final Categories categories; private final Places places; private final Items items; private final Photos photos; private final JwtTokens jwt; private final PhotoStorage storage; private final org.springframework.security.crypto.password.PasswordEncoder encoder;
 public Api(Users u,Categories c,Places p,Items i,Photos ph,JwtTokens j,PhotoStorage s,org.springframework.security.crypto.password.PasswordEncoder e){users=u;categories=c;places=p;items=i;photos=ph;jwt=j;storage=s;encoder=e;}
 @PostMapping("/auth/login") AuthResponse login(@RequestBody @jakarta.validation.Valid LoginRequest r){User u=users.findByUsername(r.username().toLowerCase()).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Credenciales inválidas"));if(!encoder.matches(r.password(),u.passwordHash))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Credenciales inválidas");return new AuthResponse(jwt.token(u),u.username,u.role.name());}
 @GetMapping("/categories") List<CategoryDto> categories(){return categories.findByActiveTrueOrderByName().stream().map(Api::category).toList();}
 @GetMapping("/categories/all") @PreAuthorize("hasRole('ADMIN')") List<CategoryDto> allCategories(){return categories.findAll().stream().map(Api::category).toList();}
 @PostMapping("/categories") @PreAuthorize("hasRole('ADMIN')") CategoryDto addCategory(@RequestBody @jakarta.validation.Valid CategoryRequest r){Category c=new Category();apply(c,r);return category(categories.save(c));}
 @PutMapping("/categories/{id}") @PreAuthorize("hasRole('ADMIN')") CategoryDto updateCategory(@PathVariable Long id,@RequestBody @jakarta.validation.Valid CategoryRequest r){Category c=categories.findById(id).orElseThrow(()->notFound("Categoría"));apply(c,r);return category(categories.save(c));}
 @GetMapping("/places") Slice<PlaceDto> list(@RequestParam(required=false) Long categoryId,@RequestParam(required=false) Long cursor,@RequestParam(defaultValue="12") int size){int limit=Math.max(1,Math.min(size,30));List<Place> all=places.findAll().stream().filter(p->categoryId==null||p.category.id.equals(categoryId)).filter(p->cursor==null||p.id<cursor).sorted(Comparator.comparing((Place p)->p.id).reversed()).limit(limit+1).toList();Long next=all.size()>limit?all.get(limit).id:null;Map<Long,PlaceMetric> metrics=metrics(all.stream().limit(limit).map(p->p.id).toList());return new Slice<>(all.stream().limit(limit).map(p->place(p,metrics.get(p.id))).toList(),next);}
 @PostMapping("/places") PlaceDto addPlace(@RequestBody @jakarta.validation.Valid PlaceRequest r,@AuthenticationPrincipal User owner){Place p=new Place();p.name=r.name();p.zone=r.zone();p.category=categories.findById(r.categoryId()).filter(c->c.active).orElseThrow(()->notFound("Categoría"));p.createdBy=owner;p.createdAt=p.updatedAt=Instant.now();return place(places.save(p));}
 @PutMapping("/places/{id}") PlaceDto editPlace(@PathVariable Long id,@RequestBody @jakarta.validation.Valid PlaceRequest r,@AuthenticationPrincipal User owner){Place p=owned(places.findDetailedById(id).orElseThrow(()->notFound("Lugar")),owner);p.name=r.name();p.zone=r.zone();p.category=categories.findById(r.categoryId()).orElseThrow(()->notFound("Categoría"));p.updatedAt=Instant.now();return place(places.save(p));}
 @DeleteMapping("/places/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void deletePlace(@PathVariable Long id,@AuthenticationPrincipal User owner){places.delete(owned(places.findDetailedById(id).orElseThrow(()->notFound("Lugar")),owner));}
 @GetMapping("/places/{id}") PlaceDto getPlace(@PathVariable Long id){Place p=places.findDetailedById(id).orElseThrow(()->notFound("Lugar"));return place(p,metrics(List.of(id)).get(id));}
 @GetMapping("/places/{id}/items") Slice<ItemDto> listItems(@PathVariable Long id,@RequestParam(required=false) Long cursor,@RequestParam(defaultValue="12") int size){places.findDetailedById(id).orElseThrow(()->notFound("Lugar"));int limit=Math.max(1,Math.min(size,30));List<Item> result=items.findByPlaceIdOrderByIdDesc(id).stream().filter(i->cursor==null||i.id<cursor).limit(limit+1).toList();Long next=result.size()>limit?result.get(limit).id:null;List<Item> page=result.stream().limit(limit).toList();Map<Long,ItemPhoto> photoMap=photos.findByItemIdIn(page.stream().map(i->i.id).toList()).stream().collect(java.util.stream.Collectors.toMap(p->p.item.id,p->p));return new Slice<>(page.stream().map(i->item(i,photoMap.get(i.id))).toList(),next);}
 @PostMapping("/places/{placeId}/items") ItemDto addItem(@PathVariable Long placeId,@RequestBody @jakarta.validation.Valid ItemRequest r,@AuthenticationPrincipal User author){Item i=new Item();i.place=places.findById(placeId).orElseThrow(()->notFound("Lugar"));i.author=author;apply(i,r);return item(items.save(i));}
 @PutMapping("/items/{id}") ItemDto editItem(@PathVariable Long id,@RequestBody @jakarta.validation.Valid ItemRequest r,@AuthenticationPrincipal User author){Item i=owned(items.findById(id).orElseThrow(()->notFound("Ítem")),author);apply(i,r);return item(items.save(i));}
 @DeleteMapping("/items/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void deleteItem(@PathVariable Long id,@AuthenticationPrincipal User author){items.delete(owned(items.findById(id).orElseThrow(()->notFound("Ítem")),author));}
 @PostMapping(value="/items/{id}/photo",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) ItemDto upload(@PathVariable Long id,@RequestPart("file") MultipartFile file,@AuthenticationPrincipal User user)throws IOException {Item i=owned(items.findById(id).orElseThrow(()->notFound("Ítem")),user);photos.findByItemId(id).ifPresent(photos::delete);ItemPhoto p=storage.store(i,file);photos.save(p);return item(i);}
 private Map<Long,PlaceMetric> metrics(List<Long> ids){if(ids.isEmpty())return Map.of();return items.metrics(ids).stream().collect(java.util.stream.Collectors.toMap(PlaceMetric::getPlaceId,m->m));} private PlaceDto place(Place p){return place(p,metrics(List.of(p.id)).get(p.id));} private PlaceDto place(Place p,PlaceMetric metric){double avg=metric==null?0:metric.getRating();long count=metric==null?0:metric.getItemCount();return new PlaceDto(p.id,p.name,p.zone,category(p.category),p.createdBy.username,Math.round(avg*10)/10d,count,p.createdAt);}
 private ItemDto item(Item i){return item(i,photos.findByItemId(i.id).orElse(null));} private ItemDto item(Item i,ItemPhoto p){return new ItemDto(i.id,i.name,i.comment,i.taste,i.price,i.venue,i.author.username,p==null?null:storage.url(p.imageBase64),p==null?null:storage.url(p.thumbnailBase64),i.createdAt);}
 private static CategoryDto category(Category c){return new CategoryDto(c.id,c.name,c.slug,c.icon,c.active);} private static void apply(Category c,CategoryRequest r){c.name=r.name();c.slug=r.slug();c.icon=r.icon();c.active=r.active();} private static void apply(Item i,ItemRequest r){i.name=r.name();i.comment=r.comment();i.taste=r.taste();i.price=r.price();i.venue=r.venue();i.updatedAt=Instant.now();if(i.createdAt==null)i.createdAt=i.updatedAt;} private static ResponseStatusException notFound(String type){return new ResponseStatusException(HttpStatus.NOT_FOUND,type+" no encontrado");} private static Place owned(Place p,User u){if(!p.createdBy.id.equals(u.id))throw new ResponseStatusException(HttpStatus.FORBIDDEN);return p;} private static Item owned(Item i,User u){if(!i.author.id.equals(u.id))throw new ResponseStatusException(HttpStatus.FORBIDDEN);return i;}
}
