package com.wherefood.web;

import com.wherefood.config.*; import com.wherefood.domain.*; import com.wherefood.repo.Repositories.*; import jakarta.validation.constraints.*; import org.springframework.http.*; import org.springframework.security.access.prepost.*; import org.springframework.security.core.annotation.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.*; import org.springframework.web.server.ResponseStatusException; import java.io.*; import java.time.*; import java.util.*;

record LoginRequest(@NotBlank String username,@NotBlank String password){} record AuthResponse(String token,String username,String role){}
record CategoryRequest(@NotBlank String name,@NotBlank String slug,@NotBlank String icon,boolean active){} record CategoryDto(Long id,String name,String slug,String icon,boolean active){}
record PlaceRequest(@NotBlank String name,String address,String sourceUrl,String mapsUrl,@NotNull Long categoryId){} record ItemRequest(@NotBlank String name,String comment,@Min(1) @Max(5) short taste,@Min(1) @Max(5) short price){}
record PlaceReviewRequest(String comment,@Min(1) @Max(5) short location,@Min(1) @Max(5) short heating,@Min(1) @Max(5) short bathrooms,@Min(1) @Max(5) short exterior,@Min(1) @Max(5) short seating,@Min(1) @Max(5) short service,@Min(1) @Max(5) short ambiance){}
record PlaceReviewDto(String author,String comment,short location,short heating,short bathrooms,short exterior,short seating,short service,short ambiance){}
record ItemDto(Long id,String name,String comment,short taste,short price,String author,String photoUrl,String thumbnailUrl,Instant createdAt){}
record PlaceDto(Long id,String name,String address,String sourceUrl,String mapsUrl,PlaceStatus status,CategoryDto category,String author,double rating,double tasteAverage,double priceAverage,double venueAverage,long itemCount,String photoUrl,String thumbnailUrl,List<PlaceReviewDto> reviews,Instant createdAt){} record Slice<T>(List<T> content,Long nextCursor){}

@RestController @RequestMapping("/api") public class Api {
 private final Users users; private final Categories categories; private final Places places; private final Items items; private final Photos photos; private final PlaceReviews reviews; private final PlacePhotos placePhotos; private final JwtTokens jwt; private final PhotoStorage storage; private final org.springframework.security.crypto.password.PasswordEncoder encoder;
 public Api(Users u,Categories c,Places p,Items i,Photos ph,PlaceReviews r,PlacePhotos pp,JwtTokens j,PhotoStorage s,org.springframework.security.crypto.password.PasswordEncoder e){users=u;categories=c;places=p;items=i;photos=ph;reviews=r;placePhotos=pp;jwt=j;storage=s;encoder=e;}
 @PostMapping("/auth/login") AuthResponse login(@RequestBody @jakarta.validation.Valid LoginRequest r){User u=users.findByUsername(r.username().toLowerCase()).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Credenciales inválidas"));if(!encoder.matches(r.password(),u.passwordHash))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Credenciales inválidas");return new AuthResponse(jwt.token(u),u.username,u.role.name());}
 @GetMapping("/categories") List<CategoryDto> categories(){return categories.findByActiveTrueOrderByName().stream().map(Api::category).toList();}
 @GetMapping("/categories/all") @PreAuthorize("hasRole('ADMIN')") List<CategoryDto> allCategories(){return categories.findAll().stream().map(Api::category).toList();}
 @PostMapping("/categories") @PreAuthorize("hasRole('ADMIN')") CategoryDto addCategory(@RequestBody @jakarta.validation.Valid CategoryRequest r){Category c=new Category();apply(c,r);return category(categories.save(c));}
 @PutMapping("/categories/{id}") @PreAuthorize("hasRole('ADMIN')") CategoryDto updateCategory(@PathVariable Long id,@RequestBody @jakarta.validation.Valid CategoryRequest r){Category c=categories.findById(id).orElseThrow(()->notFound("Categoría"));apply(c,r);return category(categories.save(c));}
 @GetMapping("/places") Slice<PlaceDto> list(@RequestParam(required=false) Long categoryId,@RequestParam(required=false) PlaceStatus status,@RequestParam(required=false) Long cursor,@RequestParam(defaultValue="12") int size){int limit=Math.max(1,Math.min(size,30));List<Place> all=places.findAll().stream().filter(p->categoryId==null||p.category.id.equals(categoryId)).filter(p->status==null||p.status==status).filter(p->cursor==null||p.id<cursor).sorted(Comparator.comparing((Place p)->p.id).reversed()).limit(limit+1).toList();Long next=all.size()>limit?all.get(limit).id:null;Map<Long,PlaceMetric> metrics=metrics(all.stream().limit(limit).map(p->p.id).toList());return new Slice<>(all.stream().limit(limit).map(p->place(p,metrics.get(p.id))).toList(),next);}
 @PostMapping("/places") PlaceDto addPlace(@RequestBody @jakarta.validation.Valid PlaceRequest r,@AuthenticationPrincipal User owner){Place p=new Place();apply(p,r);p.status=PlaceStatus.PENDING;p.category=categories.findById(r.categoryId()).filter(c->c.active).orElseThrow(()->notFound("Categoría"));p.createdBy=owner;p.createdAt=p.updatedAt=Instant.now();return place(places.save(p));}
 @PutMapping("/places/{id}") PlaceDto editPlace(@PathVariable Long id,@RequestBody @jakarta.validation.Valid PlaceRequest r,@AuthenticationPrincipal User owner){Place p=owned(places.findDetailedById(id).orElseThrow(()->notFound("Lugar")),owner);apply(p,r);p.category=categories.findById(r.categoryId()).orElseThrow(()->notFound("Categoría"));p.updatedAt=Instant.now();return place(places.save(p));}
 @DeleteMapping("/places/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void deletePlace(@PathVariable Long id,@AuthenticationPrincipal User owner){places.delete(owned(places.findDetailedById(id).orElseThrow(()->notFound("Lugar")),owner));}
 @GetMapping("/places/{id}") PlaceDto getPlace(@PathVariable Long id){Place p=places.findDetailedById(id).orElseThrow(()->notFound("Lugar"));return place(p,metrics(List.of(id)).get(id));}
 @PutMapping("/places/{id}/review") PlaceReviewDto saveReview(@PathVariable Long id,@RequestBody @jakarta.validation.Valid PlaceReviewRequest r,@AuthenticationPrincipal User author){Place p=places.findById(id).orElseThrow(()->notFound("Lugar"));PlaceReview review=reviews.findByPlaceIdAndAuthorId(id,author.id).orElseGet(()->{PlaceReview v=new PlaceReview();v.place=p;v.author=author;v.createdAt=Instant.now();return v;});apply(review,r);review.updatedAt=Instant.now();p.status=PlaceStatus.REVIEWED;places.save(p);return review(reviews.save(review));}
 @PostMapping(value="/places/{id}/photo",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) @org.springframework.transaction.annotation.Transactional PlaceDto uploadPlacePhoto(@PathVariable Long id,@RequestPart("file") MultipartFile file,@AuthenticationPrincipal User user)throws IOException {Place p=owned(places.findDetailedById(id).orElseThrow(()->notFound("Lugar")),user);placePhotos.findByPlaceId(id).ifPresent(placePhotos::delete);placePhotos.flush();placePhotos.save(storage.store(p,file));return place(p);}
 @GetMapping("/places/{id}/items") Slice<ItemDto> listItems(@PathVariable Long id,@RequestParam(required=false) Long cursor,@RequestParam(defaultValue="12") int size){places.findDetailedById(id).orElseThrow(()->notFound("Lugar"));int limit=Math.max(1,Math.min(size,30));List<Item> result=items.findByPlaceIdOrderByIdDesc(id).stream().filter(i->cursor==null||i.id<cursor).limit(limit+1).toList();Long next=result.size()>limit?result.get(limit).id:null;List<Item> page=result.stream().limit(limit).toList();Map<Long,ItemPhoto> photoMap=photos.findByItemIdIn(page.stream().map(i->i.id).toList()).stream().filter(p->p.item!=null&&p.item.id!=null).collect(java.util.stream.Collectors.toMap(p->p.item.id,p->p,(first,ignored)->first));return new Slice<>(page.stream().map(i->item(i,photoMap.get(i.id))).toList(),next);}
 @PostMapping("/places/{placeId}/items") ItemDto addItem(@PathVariable Long placeId,@RequestBody @jakarta.validation.Valid ItemRequest r,@AuthenticationPrincipal User author){Item i=new Item();i.place=places.findById(placeId).orElseThrow(()->notFound("Lugar"));i.place.status=PlaceStatus.REVIEWED;places.save(i.place);i.author=author;apply(i,r);return item(items.save(i));}
 @PutMapping("/items/{id}") ItemDto editItem(@PathVariable Long id,@RequestBody @jakarta.validation.Valid ItemRequest r,@AuthenticationPrincipal User author){Item i=owned(items.findById(id).orElseThrow(()->notFound("Ítem")),author);apply(i,r);return item(items.save(i));}
 @DeleteMapping("/items/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void deleteItem(@PathVariable Long id,@AuthenticationPrincipal User author){Item item=owned(items.findById(id).orElseThrow(()->notFound("Ítem")),author);items.delete(item);}
 @PostMapping(value="/items/{id}/photo",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) @org.springframework.transaction.annotation.Transactional ItemDto upload(@PathVariable Long id,@RequestPart("file") MultipartFile file,@AuthenticationPrincipal User user)throws IOException {Item i=owned(items.findById(id).orElseThrow(()->notFound("Ítem")),user);photos.findByItemId(id).ifPresent(photos::delete);photos.flush();ItemPhoto p=storage.store(i,file);photos.save(p);return item(i,p);}
 private Map<Long,PlaceMetric> metrics(List<Long> ids){if(ids.isEmpty())return Map.of();return items.metrics(ids).stream().collect(java.util.stream.Collectors.toMap(PlaceMetric::getPlaceId,m->m));}
 private PlaceDto place(Place p){return place(p,metrics(List.of(p.id)).get(p.id));}
 private PlaceDto place(Place p,PlaceMetric metric){double taste=metric==null?0:metric.getTasteAverage();double price=metric==null?0:metric.getPriceAverage();List<PlaceReviewDto> venueReviews=reviews.findByPlaceIdOrderByAuthorUsername(p.id).stream().map(Api::review).toList();double venue=venueReviews.stream().mapToDouble(Api::venueScore).average().orElse(0);int parts=(taste>0?1:0)+(price>0?1:0)+(venue>0?1:0);double rating=parts==0?0:((taste>0?taste:0)+(price>0?price:0)+(venue>0?venue:0))/parts;PlacePhoto photo=placePhotos.findByPlaceId(p.id).orElse(null);return new PlaceDto(p.id,p.name,p.address,p.sourceUrl,p.mapsUrl,p.status,category(p.category),p.createdBy.username,round(rating),round(taste),round(price),round(venue),metric==null?0:metric.getItemCount(),photo==null?null:storage.url(photo.imageBase64),photo==null?null:storage.url(photo.thumbnailBase64),venueReviews,p.createdAt);}
 private static double venueScore(PlaceReviewDto r){return (r.location()+r.heating()+r.bathrooms()+r.exterior()+r.seating()+r.service()+r.ambiance())/7d;}
 private static double round(double value){return Math.round(value*10)/10d;} private static void apply(Place p,PlaceRequest r){p.name=r.name();p.address=r.address();p.sourceUrl=r.sourceUrl();p.mapsUrl=r.mapsUrl();} private static void apply(PlaceReview v,PlaceReviewRequest r){v.comment=r.comment();v.location=r.location();v.heating=r.heating();v.bathrooms=r.bathrooms();v.exterior=r.exterior();v.seating=r.seating();v.service=r.service();v.ambiance=r.ambiance();}
 private ItemDto item(Item i){return item(i,photos.findByItemId(i.id).orElse(null));} private ItemDto item(Item i,ItemPhoto p){return new ItemDto(i.id,i.name,i.comment,i.taste,i.price,i.author.username,p==null?null:storage.url(p.imageBase64),p==null?null:storage.url(p.thumbnailBase64),i.createdAt);}
 private static PlaceReviewDto review(PlaceReview r){return new PlaceReviewDto(r.author.username,r.comment,r.location,r.heating,r.bathrooms,r.exterior,r.seating,r.service,r.ambiance);} private static CategoryDto category(Category c){return new CategoryDto(c.id,c.name,c.slug,c.icon,c.active);} private static void apply(Category c,CategoryRequest r){c.name=r.name();c.slug=r.slug();c.icon=r.icon();c.active=r.active();} private static void apply(Item i,ItemRequest r){i.name=r.name();i.comment=r.comment();i.taste=r.taste();i.price=r.price();i.updatedAt=Instant.now();if(i.createdAt==null)i.createdAt=i.updatedAt;} private static ResponseStatusException notFound(String type){return new ResponseStatusException(HttpStatus.NOT_FOUND,type+" no encontrado");} private static Place owned(Place p,User u){if(!p.createdBy.id.equals(u.id))throw new ResponseStatusException(HttpStatus.FORBIDDEN);return p;} private static Item owned(Item i,User u){if(!i.author.id.equals(u.id))throw new ResponseStatusException(HttpStatus.FORBIDDEN);return i;}
}
